services:
  postgres:
    image: postgres:16.9
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: adminmt
      POSTGRES_PASSWORD: adminpw
    volumes: # Mount the local `init-db.sql` file into the `init-db.sql` file at the specified container path, so it automatically seeds data into the database upon container start up
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
