micronaut:
  application:
    name: purge-scheduler

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/usersdb
    driverClassName: org.postgresql.Driver
    username: adminmt
    password: adminpw
